name: CI
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  test-token:
    needs: build
    uses: ./.github/workflows/test2.yml@main
    secrets:
      TEST_TOKEN: '${{ secrets.TEST_TOKEN }}'
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
