name: CI
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  test-token_1:
    uses: ./.github/workflows/test2.yml
    with: 
      environment: test_1
    secrets:
      TEST_TOKEN: '${{ secrets.TEST_TOKEN }}'
      
  test-token_2:
    uses: ./.github/workflows/test2.yml
    with: 
      environment: test_2
    secrets:
      TEST_TOKEN: '${{ secrets.TEST_TOKEN }}'
